Fast donation form
hyper-island-collaboration-work/yennenga-progress-group-3 pull request #24
Opened 2024-05-12 21:05 UTC by vsafonova

I finished the layout for the form and wrote the logic for showing different inputs and making the button active or disabled  depending on the form's state

2024-05-13 08:47 UTC, MoysisPap requested changes
Hi Vicka,

It seems you have similar functions(setPhone, setEmail, setRecurrence and etc) so you could rewrite them and make them the reusable to not write the same functionality for every similar function.

Thanks!

2024-05-14 02:52 UTC, HifzaBatool reviewed
Great job! Could we add some comments to provide context and clarity? It'll help future devs understand the code better. Happy to assist if needed!

2024-05-14 12:32 UTC, simon-rosengren requested changes
Hey, great job on the donation form! I agree that the previously mentioned changes would be good for maintainability and reusability of the code. 
Adding on to that, one change we could do is change the name of some variables such as amount200 and amount400 to amountSmall and amountBig? Just in case we should decide to change the amounts later on.

2024-05-15 07:47 UTC, simon-rosengren approved these changes

2024-05-15 08:04 UTC, MoysisPap approved these changes

2024-05-26 19:39 UTC, merged